
# File: .github/workflows/workflow.yml

on: [push]

name: armTemplateDeployment

jobs:

  armdeploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
   