
# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    
    - uses: actions/checkout@v2
    #- uses: azure/CLI@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/CLI@v1
      with:
        inlinescript: |
          az deployment sub create --location "eastasia" --template-file ./template.json
