name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 63b31bb9-de05-4402-9a7d-b530fd86c1af
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 63b31bb9-de05-4402-9a7d-b530fd86c1af
          template: ./arm-templates/template.json
          parameters: ./arm-templates/parameters.json
          deploymentMode: incremental